
###  1.회원 가입하기
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "email": "test8@test.com",
  "pw": "test1234",
  "username": "test8",
  "mobile": "01012341234"
}

### 2. 로그인
POST http://localhost:4000/auth/signin
Content-Type: application/json

{
  "email": "test3@test.com",
  "pw": "test1234"
}

### 3.  로그아웃
#  headers access_token 으로 토큰 전달해야함
POST http://localhost:4000/auth/logout
Content-Type: application/json

{}

###

### 4. 로그인 체크
#  headers access_token 으로 토큰 전달해야함
GET http://localhost:4000/auth/check
Accept: application/json

{}
###



###

###  audio, video file read by stream
# url: public/audio/vKLJDRv8EEWNP1ib.mp3
# url: /Users/jhnoru/yarn.lock
#
POST http://localhost:4000/file/read/media
Content-Type: application/json

{
"path": "public/audio/vKLJDRv8EEWNP1ib.mp3"
}

###


### Get Playlist
GET http://localhost:4000/playlist/kkk@kkk.com
Accept: application/json

###


### Create Playlist by id
POST http://localhost:4000/playlist
Content-Type: application/json

{
  "id": 1,
  "title": "test #1",
  "email": "kkk@kkk.com",
  "description": "test-playlist #1",
  "avatar": "test-avatar.jpg"
}

###


### Modify Playlist
PATCH http://localhost:4000/playlist
Content-Type: application/json

{
  "id": 3,
  "avatar": "good.png"
}


###
### DELETE Playlist
DELETE http://localhost:4000/playlist/2
Content-Type: application/json

{}

###
